@startuml

title "Event sourcing with projections updated using events sent through Apache Kafka"

component "PurchaseOrderService" as Service
component "PurchaseOrderRepository" as Repository
database "\n     EventStore    \n" as EventStore #LightBlue

Service -d-> Repository
Repository -> EventStore : PurchaseOrderPlaced event

queue "\n    Apache Kafka    \n" as Kafka #DimGrey
component "EventPublisher" as EventPublisher
component "PurchaseOrderProjector" as Projector
database "\n    PurchaseOrderProjections    \n" as Projections #LightBlue

EventPublisher -u-> EventStore
EventPublisher -d-> Kafka
Kafka -d-> Projector
Projector -d-> Projections
Repository -> Projections : Read queries

@enduml